name: Build and test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install python dependencies
        run: |
          pip install -r requirements.txt

      - name: validate data
        run: |
          cd model_conversion
          ./convert_and_validate.sh

      - name: Run tests
        run: |
          pytest



